[tool.poetry]
name = "calculator"
version = "0.1.0"
description = ""
authors = ["wangruoyu <wangry@tib.cas.cn>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
